---
clone:
  depth: 1
kind: pipeline
name: AzurePipeline
steps:
  -
    commands:
      - "export token=$TOKEN"
      - "curl https://raw.githubusercontent.com/L1sa-f/myscripts/master/kernel.sh | bash"
    environment:
      TOKEN:
        from_secret: token
    image: fadlyas/kernel_dockerfile
    name: Azure-Images
    trigger:
      branch:
        - default-QTI